import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function TermsPage() {
  const { lang } = useApp()

  return (
    <div className="home-page">
      <Navbar />

      <main className="page-content">
        <h1 className="page-title">
          {lang === 'en' ? 'Terms of Service' : '이용약관'}
        </h1>
        <p className="page-updated">
          {lang === 'en' ? 'Last updated: February 2026' : '최종 수정일: 2026년 2월'}
        </p>

        {lang === 'en' ? (
          <article>
            <section className="page-section">
              <h2>Acceptance of Terms</h2>
              <p>
                By accessing and using K-Culture Cat (kculturecat.cc), you accept and agree to be bound by these Terms of
                Service. If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section className="page-section">
              <h2>Description of Service</h2>
              <p>
                K-Culture Cat provides an interactive platform focused on Korean culture, including
                Korean language (TOPIK), cuisine, and traditions. Our service includes:
              </p>
              <ul>
                <li><strong>Free features:</strong> Korean culture quizzes (TOPIK, Food, Culture), learning resources — supported by advertising</li>
                <li><strong>Paid features:</strong> AI-powered Korean Style Analysis — a one-time purchase that provides personalized hairstyle and fashion recommendations based on your photos</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>Paid Services & Payment</h2>
              <p>
                Certain features of K-Culture Cat require a one-time payment. All payments are processed
                securely through <a href="https://polar.sh" target="_blank" rel="noopener noreferrer" className="inline-link">Polar</a>,
                our third-party payment processor. By making a purchase, you also agree to
                Polar's <a href="https://polar.sh/legal/terms" target="_blank" rel="noopener noreferrer" className="inline-link">Terms of Service</a>.
              </p>
              <ul>
                <li>Prices are displayed at the time of purchase and include applicable taxes</li>
                <li>Payment is required before accessing paid features</li>
                <li>You will receive a confirmation email from Polar upon successful payment</li>
                <li>We do not store your credit card or payment details — all payment information is handled directly by Polar</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>Digital Content Delivery</h2>
              <p>
                The Korean Style Analysis is a digital service delivered immediately upon payment.
                By completing your purchase, you acknowledge and agree that:
              </p>
              <ul>
                <li>The digital content/service will be provided immediately after payment</li>
                <li>Results are generated by AI and are for entertainment and reference purposes only</li>
                <li>Results may vary and are not guaranteed to match professional styling advice</li>
                <li>Once your analysis is generated, the service is considered fully delivered</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>Refund Policy</h2>
              <p>
                For information about refunds, please refer to our{' '}
                <Link to="/refund" className="inline-link">Refund Policy</Link> page.
              </p>
            </section>

            <section className="page-section">
              <h2>User Conduct</h2>
              <p>When using our service, you agree to:</p>
              <ul>
                <li>Use the service for lawful purposes only</li>
                <li>Not attempt to disrupt or interfere with the service's functionality</li>
                <li>Not reproduce, distribute, or create derivative works from our content without permission</li>
                <li>Provide accurate information when using the contact form or making purchases</li>
                <li>Not abuse the payment or refund system</li>
                <li>Not upload inappropriate, offensive, or illegal content (including photos)</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>Uploaded Content</h2>
              <p>
                When you use the Korean Style Analysis feature, you upload a photo for AI analysis.
                By uploading, you confirm that:
              </p>
              <ul>
                <li>You have the right to use and share the uploaded photo</li>
                <li>The photo is of yourself or you have consent from the person in the photo</li>
                <li>Your uploaded photo is processed solely for the purpose of generating style recommendations and is not stored permanently</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>Intellectual Property</h2>
              <p>
                All content, including questions, answers, images, AI-generated results, and design elements, is the
                intellectual property of K-Culture Cat. Unauthorized reproduction, distribution, or
                modification is prohibited.
              </p>
            </section>

            <section className="page-section">
              <h2>Disclaimer of Warranties</h2>
              <p>
                K-Culture Cat is provided "as is" without any warranties, express or implied. We do not
                guarantee that the service will be uninterrupted, error-free, or that content is
                free from inaccuracies. Quiz results and style analysis results are for educational and entertainment purposes
                only and do not constitute official certification or professional advice.
              </p>
            </section>

            <section className="page-section">
              <h2>Limitation of Liability</h2>
              <p>
                K-Culture Cat shall not be liable for any indirect, incidental, special, or consequential
                damages arising from your use of or inability to use the service, including but not limited to
                dissatisfaction with AI-generated style recommendations.
              </p>
            </section>

            <section className="page-section">
              <h2>Advertising</h2>
              <p>
                Our free features display third-party advertisements through Google AdSense. We are not
                responsible for the content of these advertisements. Your interaction with advertisers
                is solely between you and the advertiser.
              </p>
            </section>

            <section className="page-section">
              <h2>Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms of Service at any time. Continued use of
                the service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section className="page-section">
              <h2>Governing Law</h2>
              <p>
                These Terms of Service shall be governed by and construed in accordance with applicable laws.
                Any disputes arising from the use of our service shall be resolved through good-faith negotiation first.
              </p>
            </section>

            <section className="page-section">
              <h2>Contact</h2>
              <p>
                For questions about these Terms of Service, please use our{' '}
                <Link to="/about#contact-section" className="inline-link">contact form</Link>.
              </p>
            </section>
          </article>
        ) : (
          <article>
            <section className="page-section">
              <h2>약관 동의</h2>
              <p>
                K-Culture Cat(kculturecat.cc)에 접속하고 사용함으로써 본 이용약관에 동의하는 것으로 간주합니다.
                본 약관에 동의하지 않으시면 서비스를 이용하지 마시기 바랍니다.
              </p>
            </section>

            <section className="page-section">
              <h2>서비스 설명</h2>
              <p>
                K-Culture Cat은 한국어(TOPIK), 음식, 전통 등 한국 문화에 초점을 맞춘 인터랙티브
                플랫폼을 제공합니다. 서비스 구성은 다음과 같습니다:
              </p>
              <ul>
                <li><strong>무료 기능:</strong> 한국 문화 퀴즈(TOPIK, 음식, 문화), 학습 자료 — 광고로 운영</li>
                <li><strong>유료 기능:</strong> AI 한국 스타일 분석 — 사진을 기반으로 맞춤형 헤어스타일 및 패션 추천을 제공하는 1회 결제 서비스</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>유료 서비스 및 결제</h2>
              <p>
                K-Culture Cat의 일부 기능은 1회 결제가 필요합니다. 모든 결제는 제3자 결제 처리업체인{' '}
                <a href="https://polar.sh" target="_blank" rel="noopener noreferrer" className="inline-link">Polar</a>를
                통해 안전하게 처리됩니다. 결제 시{' '}
                <a href="https://polar.sh/legal/terms" target="_blank" rel="noopener noreferrer" className="inline-link">Polar 이용약관</a>에도
                동의하는 것으로 간주됩니다.
              </p>
              <ul>
                <li>가격은 구매 시점에 표시되며 해당 세금이 포함됩니다</li>
                <li>유료 기능 이용 전 결제가 필요합니다</li>
                <li>결제 성공 시 Polar로부터 확인 이메일을 받으실 수 있습니다</li>
                <li>신용카드 및 결제 정보는 당사에 저장되지 않으며, 모든 결제 정보는 Polar에서 직접 처리합니다</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>디지털 콘텐츠 제공</h2>
              <p>
                한국 스타일 분석은 결제 즉시 제공되는 디지털 서비스입니다.
                구매를 완료함으로써 다음에 동의하는 것으로 간주됩니다:
              </p>
              <ul>
                <li>디지털 콘텐츠/서비스는 결제 후 즉시 제공됩니다</li>
                <li>결과는 AI에 의해 생성되며 오락 및 참고 목적으로만 사용됩니다</li>
                <li>결과는 다를 수 있으며 전문 스타일링 조언과 일치한다고 보장하지 않습니다</li>
                <li>분석이 생성되면 서비스가 완전히 제공된 것으로 간주됩니다</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>환불 정책</h2>
              <p>
                환불에 대한 자세한 내용은{' '}
                <Link to="/refund" className="inline-link">환불 정책</Link> 페이지를 참조하세요.
              </p>
            </section>

            <section className="page-section">
              <h2>이용자 행동 규범</h2>
              <p>서비스 이용 시 다음에 동의합니다:</p>
              <ul>
                <li>합법적인 목적으로만 서비스를 사용</li>
                <li>서비스 기능을 방해하거나 간섭하지 않음</li>
                <li>허가 없이 콘텐츠를 복제, 배포 또는 2차 저작물을 만들지 않음</li>
                <li>문의 양식 사용 또는 구매 시 정확한 정보 제공</li>
                <li>결제 또는 환불 시스템을 남용하지 않음</li>
                <li>부적절하거나 불쾌하거나 불법적인 콘텐츠(사진 포함)를 업로드하지 않음</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>업로드된 콘텐츠</h2>
              <p>
                한국 스타일 분석 기능을 사용할 때 AI 분석을 위해 사진을 업로드합니다.
                업로드함으로써 다음을 확인합니다:
              </p>
              <ul>
                <li>업로드하는 사진을 사용하고 공유할 권리가 있음</li>
                <li>사진이 본인의 것이거나 사진 속 인물의 동의를 받았음</li>
                <li>업로드된 사진은 스타일 추천 생성 목적으로만 처리되며 영구적으로 저장되지 않습니다</li>
              </ul>
            </section>

            <section className="page-section">
              <h2>지적재산권</h2>
              <p>
                문제, 답변, 이미지, AI 생성 결과물 및 디자인 요소를 포함한 모든 콘텐츠는 K-Culture Cat의
                지적재산입니다. 무단 복제, 배포 또는 수정은 금지되어 있습니다.
              </p>
            </section>

            <section className="page-section">
              <h2>보증의 부인</h2>
              <p>
                K-Culture Cat은 명시적이든 묵시적이든 어떠한 보증 없이 "있는 그대로" 제공됩니다.
                서비스가 중단 없이, 오류 없이 제공되거나 콘텐츠에 부정확성이 없음을 보장하지
                않습니다. 퀴즈 결과 및 스타일 분석 결과는 교육 및 오락 목적이며 공식 인증이나 전문적인 조언을 구성하지 않습니다.
              </p>
            </section>

            <section className="page-section">
              <h2>책임의 제한</h2>
              <p>
                K-Culture Cat은 서비스 사용 또는 사용 불능으로 인한 간접적, 부수적, 특별 또는
                결과적 손해에 대해 책임지지 않습니다. 이는 AI 생성 스타일 추천에 대한
                불만족을 포함하되 이에 국한되지 않습니다.
              </p>
            </section>

            <section className="page-section">
              <h2>광고</h2>
              <p>
                무료 기능에는 Google AdSense를 통해 제3자 광고가 게재됩니다. 해당 광고의 내용에
                대해 책임지지 않습니다. 광고주와의 상호작용은 전적으로 귀하와 광고주 간의 문제입니다.
              </p>
            </section>

            <section className="page-section">
              <h2>약관 변경</h2>
              <p>
                본 이용약관을 언제든지 수정할 수 있는 권리를 보유합니다. 변경 후 서비스를
                계속 사용하면 새 약관에 동의한 것으로 간주됩니다.
              </p>
            </section>

            <section className="page-section">
              <h2>준거법</h2>
              <p>
                본 이용약관은 관련 법률에 따라 규율되고 해석됩니다.
                서비스 이용으로 인한 분쟁은 먼저 성실한 협의를 통해 해결합니다.
              </p>
            </section>

            <section className="page-section">
              <h2>문의</h2>
              <p>
                본 이용약관에 대한 질문이 있으시면{' '}
                <Link to="/about#contact-section" className="inline-link">문의 양식</Link>을 통해 연락해 주세요.
              </p>
            </section>
          </article>
        )}
      </main>

      <Footer />
    </div>
  )
}
